name: agents_app
description: "VerifiX - Field Verification Network"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
